
require: rubocop-rails
AllCops:
    TargetRubyVersion: 2.6
    Exclude:
      - 'Guardfile'
      - 'bin/*'
      - 'node_modules/**/*'
      - 'vendor/**/*'
      - 'db/seed_data.rb'
      - 'db/schema.rb'
      - 'config/routes.rb'

Rails:
    Enabled: true

Gemspec/RequiredRubyVersion:
    Enabled: true

# No space makes the method definition shorter and differentiates
# from a regular assignment.
Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space

# Most readable form.
Layout/HashAlignment:
    EnforcedHashRocketStyle: table
    EnforcedColonStyle: table

Layout/LineLength:
    Max: 120

Layout/IndentationWidth:
  Width: 4 # 4 spaces for Indentation.

Lint/RaiseException:
    Enabled: true

Lint/StructNewOverride:
    Enabled: true

Metrics/BlockLength:
    ExcludedMethods: ['describe', 'context', 'shared_examples', 'namespace', 'ActiveRecord::Schema.define']

# Skips style of child classes and modules.
Style/ClassAndModuleChildren:
    Enabled: false

Style/CollectionMethods:
    Enabled: true
    PreferredMethods:
        # inject seems more common in the community.
        reduce: "inject"

Style/Documentation:
    Enabled: false

Style/HashEachMethods:
    Enabled: true
    AutoCorrect: false # Unsafe autocorrect

Style/HashTransformKeys:
    Enabled: true
    AutoCorrect: false # Unsafe autocorrect

Style/HashTransformValues:
    Enabled: true
    AutoCorrect: false # Unsafe autocorrect

# Mixing the styles looks just silly.
Style/HashSyntax:
    EnforcedStyle: ruby19_no_mixed_keys

# has_key? and has_value? are far more readable than key? and value?
Style/PreferredHashMethods:
    EnforcedStyle: verbose

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true
Layout/SpaceAroundMethodCallOperator:
    Enabled: true
Style/ExponentialNotation:
    Enabled: true
Style/SlicingWithRange:
    Enabled: true

Metrics/MethodLength:
    Max: 20
    Exclude:
        - 'db/seed_data.rb'

Metrics/ModuleLength:
    Exclude:
        - 'db/seed_data.rb'

# Version 0.85.0
Lint/DeprecatedOpenSSLConstant:
    Enabled: true
Lint/MixedRegexpCaptureTypes:
    Enabled: true
Style/RedundantRegexpCharacterClass:
    Enabled: true
Style/RedundantRegexpEscape:
    Enabled: true

